openapi: 3.0.3
info:
  title: Post Service API
  description: API for managing posts.
  version: 1.0.0
servers:
  - url: https://2vtvpj15ii.execute-api.us-east-1.amazonaws.com/prod
    description: Main server
paths:
  /posts/{postId}:
    get:
      summary: Get Post by ID
      description: Retrieves information about a post by its identifier.
      parameters:
        - name: postId
          in: path
          required: true
          description: The identifier of the post
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Invalid post identifier
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Post not found
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

    delete:
      summary: Delete Post by ID
      description: Deletes a post by its identifier.
      parameters:
        - name: postId
          in: path
          required: true
          description: The identifier of the post
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Invalid post identifier
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Post not found
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

  /posts:
    post:
      summary: Create a New Post
      description: Creates a new post.
      requestBody:
        description: Data to create a new post
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCreateDto'
      responses:
        '201':
          description: Post successfully created
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

    get:
      summary: Get All Posts
      description: Retrieves a list of all posts.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string

    PostCreateDto:
      type: object
      properties:
        title:
          type: string
        content:
          type: string